# Generated by Django 5.1.2 on 2024-10-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="split_method",
            field=models.CharField(
                choices=[
                    ("EQUAL", "Equal"),
                    ("EXACT", "Exact"),
                    ("PERCENTAGE", "Percentage"),
                ],
                default="EQUAL",
                max_length=25,
            ),
        ),
    ]
